docs/guides/node-operator-manual.md
Keeping Node Operator tools information and other things updated.
=> Node Operator guide up-to-date information

docs/deployed-contracts.md
Proper name is `DepositSecurityModule`
=> Fix typo in Deposit Security Module name

docs/deployed-contracts.md
Pull adds address of the ACL proxy contract for the Lido DAO
=> Add Aragon ACL address

docs/deployed-contracts.md
Pull puts the protocol contracts first in the list, and defines a section for the DAO contracts
=> Change the order of the deployed contracts list

docs/guides/easy-track-guide.md
Adding the section on checking the motion start txs from the Gnosis Safe UI
=> Add notes on Easy Track

.github/workflows/build.yml
Uses `lts` node version that can build up to date dependencies.
=> Workflows Rework

docs/deployed-contracts.md
Adding reWARDS multisig address to docs
=> Add rewards multisig address

docs/guides/node-operator-manual.md, docs/guides/oracle-operator-manual.md
- Correct Oracle version for Testnet
- Official CLI everywhere instead of our fork
- Correct CLI instructions
- WC information improvements
=> Outdated info fixes

docs/guides/checking-aragon-vote.md, sidebars.js
Adding doc for checking evm scripts in vote with replit
=> Add howto for checking evm script on aragon vote

docs/guides/oracle-operator-manual.md
New version Lido Oracle is going to be released. Update documentation according updates in Oracle
=> Lido Oracle - documentation update

docs/deployed-contracts.md
Changing bETH addresses after migration to Wormhole
=> Update addresses after bETH wormhole migration

docs/deployed-contracts.md
Adding bETH token address to the docs
=> Add bETH address

docs/deployed-contracts.md
Changing impl address after migration
=> Update the AnchorVault impl address

docs/deployed-contracts.md
To be used to recover funds from 1inch rewarder
=> Doc: add tokens recoverer on mainnet for Reward Program's managers

docs/deployed-contracts.md
We have the following versions:
1.0.0: current
2.0.0: upcoming (allows voting time changes)
Context:
* https://research.lido.fi/t/increase-aragon-voting-duration-to-72-hours-operation-plan/1915
=> Doc: add voting impl alternative

docs/deployed-contracts.md
The pool is deployed on curve with high A coef.
Context: https://twitter.com/LidoFinance/status/1524826418571534336
=> Doc: add the deployed concetrated steth/weth curve pool

docs/contracts/lido-execution-layer-rewards-vault.md, docs/contracts/lido.md, docs/guides/protocol-levers.md
This PR features some wording and typo fixes.
=> docs: correct some wording and typos

docs/guides/node-operator-manual.md
Reflect the name change on the deposit-cli tool
https://github.com/ethereum/staking-deposit-cli
=> rename eth2.0-deposit-cli to staking-deposit-cli

docs/deployed-contracts.md
As part of [Last minute vote mitigation proposal](https://research.lido.fi/t/proposal-last-minute-vote-mitigation/2162/16) going to add a newly deployed Voting contract as proposed to the list
=> Add Voting proposed implementation

docs/guides/checking-gnosis-safe.md, sidebars.js
Adding a guide for validating Gnosis safe deployments
=> Checking gnosis safe validity

docs/deployed-contracts.md
Sharing initial deployment addresses for the first batch of L2 bridging for WstETH
=> L2s Initial deployment addresses

docs/deployed-contracts.md
Adding rewards multisigs for L2s
=> docs: add rewards on L2s

docs/deployed-contracts.md
Small fix for deployed addresses
=> Odd dash removal

.vscode/settings.json, docs/integrations/subgraph.md
@kolysapphire.  Made changes and added subgraph info and links to existing subgraph file and also added query examples.
=> Improved Subgraph Docs

docs/deployed-contracts.md
=> feat: add proposed insurance fund address

docs/guides/steth-integration-guide.md
https://www.notion.so/Insurance-docs-lido-fi-98f3b3e8f80f43c7840400cb3cf6f411
=> feat: steth-integration-guide.md changes

docs/guides/address-ownership-guide.md, docs/guides/multisig-signer-manual.md, sidebars.js
Guides to get proove the address is under your control.+ general rules of thumb for multisig operations
=> Adding guides on how to multisig

docs/guides/address-ownership-guide.md
Fix for a typo in address verification doc
=> Fixing typo in address verification process doc

docs/guides/steth-integration-guide.md, docs/integrations/aave/aip.md, docs/security/bugbounty.md
Change texts a bit in several files
=> fix: wording in several files

docs/deployed-contracts.md
The address should be in the deployed contracts list.
=> Fix: add InsuranceFund goerli address

docs/deployed-contracts.md
Adding new EasyTrack motion contracts as proposed
=> Add addresses of the new Easy Track motions contracts

docs/introduction.mdx
https://linear.app/lidofi/issue/UI-219/replace-ethereum-staking-rewards-section-with-apr-visualization
=> feat: add Protocol APR section to introduction page

docs/lido-dao.md
There's no LDO staking in Lido DAO contracts
=> Correct info around LDO staking

docs/guides/steth-integration-guide.md
- Added wstETH on L2s paragraph
- Added Goerli wstETH for testing paragraph
=> wstETH on Goerli and L2s

docs/guides/steth-integration-guide.md
- mentioned wstETH shortcut on goerli
=> - wstETH on Goerli

docs/deployed-contracts/index.md
Forum thread to check the address: https://research.lido.fi/t/proposal-to-form-rewards-committee/1447/30
=> Added reWARDS OP Token multisig

docs/deployed-contracts/goerli.md
see https://github.com/lidofinance/lido-dao/blob/44a1c8a5fc1277ee010f0176c1c402d0c19a5501/deployed-goerli.json
=> update goerli addresses: DSM, sanity checker, daemon config

docs/deployed-contracts/goerli.md
Paste the new address of `OracleReportSanityChecker`.
=> Fix: update sanity checker address

docs/introduction.mdx
Legal updates of docs introduction page
=> feat: update intro according to legal

docs/deployed-contracts/goerli.md
For the reference:
https://github.com/lidofinance/lido-dao/blob/07a309dc90425684992399f26334ecdebcc2c9bb/deployed-goerli.json
=> Deploy: update burner and sanchecker on Goerli

docs/deployed-contracts/mainnet-lido-v2-proposed.md, docs/guides/verify-lido-v2-upgrade-manual.md, docs/guides/verify-shapella-upgrade-manual.md, sidebars.js
Configuration of the Lido Shapella Upgrade.
Going to have two sections:
- the parameters
- manual for verification of various technical parts of the upgrade (`lidofinance/scripts` tests configuration, etc)
=> Shapella Upgrade Verification Manual

docs/deployed-contracts/index.md
Safe description lives here:
https://research.lido.fi/t/proposal-to-form-rewards-committee/1447/36
=> Add ARB grant msig address

docs/guides/steth-integration-guide.md
Added a link to APR calculation for V2
=> APR calculation for V2

docs/integrations/api.md
Removing the limits notice and adding a link to playgroung.
=> Now working Reward History Backend on Goerli

docs/deployed-contracts/goerli.md
fix goerli ET gas supply steth addresses
https://www.notion.so/Easy-Track-setup-for-Gas-Supply-in-stETH-a0be13729d9c4750990384cc071940d8?pvs=4
=> fix goerli ET gas supply steth addresses

package.json, yarn.lock
Docusaurus 2.0.0-beta.14 => 2.4.1
=> Bump: docusaurus and browsetlists-db

docs/contracts/lido.md
=> Chore: markup errors

docs/guides/jumpgates.md
=> fix: typo in jumpgates.md

docs/contracts/lido.md, docs/guides/steth-integration-guide.md
Minor corrections for the lido and the integration guide (rephrasing, grammar, and spelling).
Also, added an oracle delay corner case to the integration guide.
=> lido and integration guide corrections

docs/contracts/trp-vesting-escrow.md
=> Chore: polish TRP vestring escrow

docs/guides/easy-track-guide.md
Fixed Easy Track guide to feature LOL (Liquidity Observation Lab) instead of reWARDS
=> rename reWARDS to LOL

docusaurus.config.js, package.json, yarn.lock
Fix the broken link for https://docs.lido.fi/guides/steth-integration-guide
=> Fix: redirect for integration guide

docs/deployed-contracts/holesky.md, sidebars.js
=> Feat: holesky deploy

docs/deployed-contracts/index.md
Add Base L2 deployment proposed addresses according to https://research.lido.fi/t/wsteth-deployment-to-base-and-ownership-acceptance-by-lido-dao/5668/1
=> feat: add L2 Base proposed addresses (for WstETH)

docs/deployed-contracts/goerli.md, docs/deployed-contracts/index.md
References for Mainnet:
- proposal: https://research.lido.fi/t/wsteth-deployment-to-base-and-ownership-acceptance-by-lido-dao/5668
- snapshot: https://snapshot.org/#/lido-snapshot.eth/proposal/0x8b35f64fffe67f67d4aeb2de2f3351404c54cd75a08277c035fa77065b6792f4
Reference for Görli:
- notion: https://www.notion.so/wstETH-on-Base-Deployment-Verification-a34fb346d53a434ba6f46448f6298f00?pvs=4#16fe3455ebe54d1ba7c6e0aef87a08e9
=> Doc: wstETH on Base

docs/guides/lido-tokens-integration-guide.md
Add a note regarding the mitigation of permitted withdrawals griefing issue https://github.com/lidofinance/lido-dao/issues/803
=> feat(integration guide): add note on withdrawals griefing issue

docs/deployed-contracts/goerli.md, docs/deployed-contracts/index.md
The proposed deployment of `wstETH` on Mantle.
Context: https://research.lido.fi/t/wsteth-deployment-on-mantle/5991
---
:warning: The verification is in progress and should've been completed by Jan 3rd.
Please don't merge the PR before that.
=> Doc: wstETH on Mantle proposed addresses

docs/deployed-contracts/index.md
Adding new LOL m-sigs on BNB and Linea. Source: https://research.lido.fi/t/liquidity-observation-lab-lol-liquidity-strategy-and-application-to-curve-steth-eth-pool/5335/8?u=grstepanov
=> Add more LOL msigs

docs/deployed-contracts/sepolia.md, sidebars.js
=> Doc: Sepolia deployment [WIP]

.github/CODEOWNERS, docs/multisigs/committees.md, docs/multisigs/emergency-brakes.md, docs/multisigs/lido-contributors-group.md, docs/multisigs/lido-on-x.md, docs/multisigs/other.md
- right alignment removed for correct displayment of tables (all pages)
- carvas removed from ATC msig and msig move to 4/6 mode. To check: https://app.safe.global/settings/setup?safe=eth:0x9B1cebF7616f2BC73b47D226f90b01a7c9F86956
- Rewards Share msig updated based on the forum and current status.
To check
safe: https://app.safe.global/settings/setup?safe=eth:0xe2A682A9722354D825d1BbDF372cC86B2ea82c8C
forum: https://research.lido.fi/t/tiered-rewards-share-program-a-sustainable-approach-to-steth-growth/4851/21
=> fix alignment in tables

docs/deployed-contracts/index.md, docs/introduction.mdx, docs/security/bugbounty.md, src/components/grid.css
=> Doc: remove Lido on Solana

docs/deployed-contracts/goerli.md
https://twitter.com/LidoFinance/status/1758458433303351784
=> Fix: goerli warning

docs/deployed-contracts/sepolia.md
Update SepoliaDepositAdapter address
=> Update SepoliaDepositAdapter addr

docs/deployed-contracts/index.md
1. remove sDVT proposed marks, 
2. add Aragon PM address
=> sDVT remove proposed marks, add Aragon PM address

docs/ipfs/ipfs-apps-list.md, docs/ipfs/ipfs-guide.md, sidebars.js
The list page with all up-to-date lido IPFSapps
=> docs: ipfs apps list, ipfs category

docs/deployed-contracts/index.md, docs/deployed-contracts/sepolia.md
The PR is prepared in response to the following proposal: https://research.lido.fi/t/wsteth-deployment-on-scroll/6603
---
Contributors' maintained notion doc: https://www.notion.so/wstETH-on-Scroll-9cacc8be21eb44e3b49898e590f37bd9
Diffyscan PR: https://github.com/lidofinance/diffyscan/pull/35
The following list of artifacts describes the changes:
- Mainnet
- Sepolia
=> Feat: add wstETH on Scroll

docs/ipfs/apps-list.md
Add Stake Widget IPFS CID and release link
=> feat: add Stake Widget IPFS hash

docs/deployed-contracts/index.md
Add proposed Stonks contracts and proposed ET factories for Lido Stonks
Forum post: https://research.lido.fi/t/lido-stonks-treasury-swaps-via-optimistic-governance/6860
Deploy plan: https://www.notion.so/Stonks-deploy-plan-37a8a7e7d3324bd6ac3dd6ff7cfe76c6
=> Add proposed Lido Stonks contracts

docs/integrations/api.md, docs/integrations/sdk.md, docs/integrations/subgraph.md, docs/integrations/wallets.md
Update:
- SDK page (add new SDK links)
- API page (add Holesky links)
- Subgraph (change URL to new one after moving to L2)
- Wallets (remove embedding example)
=> feat: update integrations docs

docs/ipfs/apps-list.md
Update
- Stake Widget IPFS CID **bafybeibobqcno4ebv2o42krcaktcsk4znpbesmcwprfp5vqqmxzuofwnuy**
=> feat: update Stake Widget IPFS CID

docs/deployed-contracts/index.md, docs/deployed-contracts/sepolia.md
⚠️: merge no earlier than [the snapshot](https://snapshot.org/#/lido-snapshot.eth/proposal/0xcdb7d84ea80d914a4abffd689ecf9bdc4bb05d47f1fdbdda8793d555381a0493) is successful
=> Remove "proposed" for scroll deployed contracts

docs/multisigs/committees.md, docs/multisigs/emergency-brakes.md
Adding information about new ET factories for TMC 
to check: 
https://research.lido.fi/t/lido-stonks-treasury-swaps-via-optimistic-governance/6860
https://docs.lido.fi/deployed-contracts/#easy-track-factories-for-token-transfers
And correcting minor typos here and there
=> add_new_ET_to_TMC_msig

docs/deployed-contracts/index.md, docs/multisigs/committees.md
To the deployed contracts page
=> Add lol on scroll multisig

docs/introduction.mdx
Delete "our" from introduction
=> fix: introduction wording

.github/workflows/build.yml, .github/workflows/deploy.yml, README.md, package.json, yarn.lock
=> Bump: update package versions

package.json, yarn.lock
See: https://docusaurus.io/blog/releases/3.2
=> Feat: bump docusaurus version to 3.2

docs/deployed-contracts/index.md
action plan https://www.notion.so/Gate-Seal-Change-action-plan-f9a48eff61854fa682a602a8573c58bd?pvs=4
=> Gate Seal change

docs/multisigs/committees.md
Optimized the list of LoL multisigs; you can check their correctness here: https://research.lido.fi/t/liquidity-observation-lab-lol-liquidity-strategy-and-application-to-curve-steth-eth-pool/5335/11
I also slightly adjusted the wording to more accurately reflect the purposes of msigs
=> Optimize LoL msigs

docs/multisigs/other.md
Change community lifeguard initiative lead in CLI msig. 
To check: 
https://research.lido.fi/t/lido-community-lifeguards-initiative/4678/44
and msig itself https://app.safe.global/settings/setup?safe=eth:0x6faCCcE132d5C397068807Ca73883d3df198dFF4
=> CLI lead change 

docs/ipfs/apps-list.md
Updates link to latest stake widget IPFS release
=> docs: update stake widget ipfs release

docs/deployed-contracts/holesky.md
Gateseal contract address changed 
New address 0x384E75097C31F9d97aaeb79c82b1FFF81Ce6dB8C (https://holesky.etherscan.io/address/0x384e75097c31f9d97aaeb79c82b1fff81ce6db8c)
=> Gateseal contract address changed

docs/deployed-contracts/holesky.md
GateSeal address is changed to 0xA34d620EA9F3e86bf8B8a7699B4dE44CD9D3202d
https://holesky.etherscan.io/address/0xA34d620EA9F3e86bf8B8a7699B4dE44CD9D3202d
=> chahged GateSeal address

docs/deployed-contracts/sepolia.md
Adding a.DI setup on Sepolia / Binance Testnet
=> doc: add a.DI setup for Sepolia <=> Binance Testnet to deployed contracts

docs/deployed-contracts/sepolia.md
=> chore: rename Binance to BSC

docs/guides/lido-tokens-integration-guide.md
- Update stETH/ETH liquidity pool on Curve link
- Update wstETH/ETH pool on Uniswap V3 link
=> docs: update lido-tokens-integration-guide.md

docs/deployed-contracts/holesky.md, docs/deployed-contracts/sepolia.md
=> Doc: disambiguate testnet purposes

.github/workflows/deploy.yml
=> Fix: deploy workflow with corepack yarn

docs/deployed-contracts/index.md, docs/multisigs/committees.md
Add Arbutrum LTIPP grant acceptance multisig to the deployed contracts and multisigs doc pages
=> add LTIPP grant msig

docs/integrations/api.md, docs/integrations/sdk.md
- Add WWT to API page
- Add Documentation link for SDK
Please review WWT description
=> feat: add wwt to api, add sdk docs

docs/contracts/insurance.md, docs/staking-modules/csm/join-csm.md, sidebars.js
- added InsuranceFund contract desc
- changed [fund] link in CSM
=> add InsuranceFund contract description

docs/guides/lido-tokens-integration-guide.md, docs/token-guides/wsteth-bridging-guide.md
=> Doc: update guides

docs/multisigs/other.md
Adding dgusakov and Aleksandra_G, updating threshold, adding links for forum and Snapshot
=> Update of CLI details

docs/deployed-contracts/index.md, docs/deployed-contracts/sepolia.md
Add the wstETH on BSC addresses according to the proposal posted: 
- Mainnet: https://research.lido.fi/t/wormhole-x-axelar-lido-bridge-implementation-for-wsteth-on-bnb-chain/6012/31
- Testnet: https://research.lido.fi/t/wormhole-x-axelar-lido-bridge-implementation-for-wsteth-on-bnb-chain/6012/32
=> Doc: add wstETH on BSC deployments

docs/deployed-contracts/index.md, docs/deployed-contracts/sepolia.md, docs/multisigs/emergency-brakes.md
Based on https://research.lido.fi/t/wsteth-deployment-on-mode/7365
=> feat(deployed-addresses): add Mode Mainnet and Sepolia addresses

docs/deployed-contracts/index.md
=> Fix multisig links

docs/contracts/deposit-security-module.md, docs/deployed-contracts/index.md, docs/deployed-contracts/sepolia.md, docs/guides/lido-tokens-integration-guide.md, docs/multisigs/committees.md, docs/multisigs/emergency-brakes.md, docs/token-guides/wsteth-bridging-guide.md
- https://snapshot.org/#/lido-snapshot.eth/proposal/0xcc52cdc83273b42a056cfc632889355595821a2cc9a59ba8adff66b30e9718f9
- https://snapshot.org/#/lido-snapshot.eth/proposal/0x6bc51c2b07a9345a03a0bc0acb72ccc9f63879c981f3a6954164d110c5d330b2
- missing networks
- don't use 'we'
- support rebranding of `zkSync Era` to `ZKSync`
- `TheDZon` ⇒ `TheDZhon` for my handle :hugs:
=> Fix: update Lido Multichain contracts

docs/deployed-contracts/sepolia.md
Update bridge and tokens contracts for Optimism Sepolia
=> doc: update optimism sepolia contracts

docs/introduction.mdx
=> typo | Update introduction.mdx

docs/guides/lido-tokens-integration-guide.md
=> link to audit | Update lido-tokens-integration-guide.md

docs/integrations/wallets.md
Return embed example to integrations docs
=> feat: return embed example

docs/deployed-contracts/sepolia.md
Update sepolia deposit contract address
=> Update sepolia deposit contract address

docs/guides/oracle-operator-manual.md
Replace Rated with Matrixed.Link
=> Update oracle members

docs/deployed-contracts/index.md, docs/guides/verify-steth-on-optimism-upgrade-manual.md, sidebars.js
Add new contract addresses
- https://www.notion.so/stETH-on-Mainnet-Optimism-deploy-plan-d03ff0382e584a49b16fe38ba34b76e7
- https://www.notion.so/stETH-on-Optimism-upgrade-announcement-and-action-plan-e7179cac8fa347959a4432e36cc0cd97
=> stETH on Optimism new contract with proposed mark

docs/contracts/legacy-oracle.md, docs/deployed-contracts/index.md
:saluting_face: 
Context:
- [stETH on Optimism upgrade announcement and action plan](https://research.lido.fi/t/steth-on-optimism-upgrade-announcement-and-action-plan/8474)
- [Deploy plan](https://www.notion.so/stETH-on-Mainnet-Optimism-deploy-plan-GTM-14-October-d03ff0382e584a49b16fe38ba34b76e7?pvs=4#e00898634b5d461a9dc313d01ff5440a)
=> Doc: legacy oracle deprecation

docs/deployed-contracts/index.md, docs/guides/lido-tokens-integration-guide.md, docs/token-guides/wsteth-bridging-guide.md
**NB:** Please don't merge till the [vote 179 gets enacted](https://vote.lido.fi/vote/179) :warning: 
---
Context: 
- https://research.lido.fi/t/steth-on-optimism-upgrade-announcement-and-action-plan/8474
- https://research.lido.fi/t/lip-22-steth-on-l2/6855
Changes:
=> Fix: stETH on Optimism

docs/multisigs/committees.md
Please double check links before approving the PR
New LOL for AAVE multisigs are presented here - **https://research.lido.fi/t/liquidity-observation-lab-lol-liquidity-strategy-and-application-to-curve-steth-eth-pool/5335/17?u=alex_l**
Changes in Rewards 2024 signers - https://research.lido.fi/t/rewards-share-program-2024/6812/18
=> Updates to Rewards Share and LOL committees

README.md, docs/security/audits.md, docusaurus.config.js, package-lock.json, package.json, scripts/fetch-audits.js, sidebars.js
=> Feat: add external fetch for audits

docs/deployed-contracts/index.md, docs/multisigs/committees.md
DO NOT MERGE unless the vote is enacted
=> feat: SR + CSM contracts proposed -> actual

docs/guides/tooling.md
Hashes could be checked in next PR:
https://github.com/lidofinance/audits/pull/86
=> Oracle version to latest

docs/guides/tooling.md
Commit could be checked in 
https://github.com/lidofinance/audits/blob/main/MixBytes%20Lido%20Oracle%20Security%20Audit%20Report%2010-24.pdf
=> Fix Oracle latest adudited commit

docs/guides/tooling.md
Audit:
https://github.com/lidofinance/audits/pull/87/files
=> Update Lido Oracle to v4.1.0

docs/contracts/accounting-oracle.md, docs/contracts/gate-seal.md, docs/contracts/legacy-oracle.md, docs/contracts/validators-exit-bus-oracle.md, docs/guides/depositor-bot.md, docs/guides/oracle-spec/accounting-oracle.md, docs/guides/oracle-spec/validator-exit-bus.md
This pull request addresses minor typographical errors in various documentation files across the repository. Each commit includes a specific typo correction in the corresponding file.
- Corrected typos in `accounting-oracle.md`
- Fixed typographical errors in `gate-seal.md`
- Corrected minor issues in `legacy-oracle.md`
- Fixed typos in `validators-exit-bus-oracle.md`
- Fixed duplicate typo correction in `accounting-oracle.md`
- Corrected typos in `validator-exit-bus.md`
- Updated `depositor-bot.md` with typo corrections
**Note:** No functional code changes were made, only documentation updates.
=> Fix: Typos in Documentation Files

package-lock.json, package.json
See: https://docusaurus.io/blog/releases/3.6
=> Feat: bump docusaurus to 3.6

docs/deployed-contracts/index.md
=> Fix: add polygon pos addresses

docs/deployed-contracts/index.md, docs/deployed-contracts/sepolia.md
Context: https://research.lido.fi/t/nec-1-recognition-of-wsteth-bridge-endpoints-on-starknet-as-canonical/8956
Sepolia contracts: https://research.lido.fi/t/wsteth-deployment-on-starknet/6335/9
=> Feat: wstETH on Starknet

docs/deployed-contracts/index.md, docs/deployed-contracts/sepolia.md
Context: https://x.com/LidoFinance/status/1864701681339895855
=> Fix: remove proposed marks

docs/deployed-contracts/index.md
Update Linea bridge addresses.
https://docs.linea.build/release-notes#alpha-v4
=> doc: update bridge addresses

docs/multisigs/committees.md
Check the list of signers approved by DAO here: https://snapshot.box/#/s:lido-snapshot.eth/proposal/0xa502cf80451192672313911ce558e74799626da3b3b66130e21c6cd19707e584
Check the signers here: https://research.lido.fi/t/establish-a-public-delegate-platform-and-delegate-incentivization-program/7858/41
Check the msig here: https://app.safe.global/home?safe=eth:0x13600b9AEE86f8254969918B1E9ae6ea091b8727
=> Delegate Oversight Committee Multisig

docs/deployed-contracts/sepolia.md
Add new contract for Soneium testnet Minato
https://www.notion.so/Verify-Soneium-Minato-17cbf633d0c9804097fdd42e9f0709ac?pvs=4
=> Soneium Minato contracts

package-lock.json, package.json
Context: https://docusaurus.io/blog/releases/3.7
=> Fix: bump docusaurus to 3.7

docs/lips.md, docs/security/audits.md
=> Fix: sync lips and audits

docs/security/audits.md, scripts/fetch-audits.js
Sort audit files in descending order.
=> Fix: sort desc audits

docusaurus.config.js
=> Revert "Update github link in docusaurus.config.js"

docs/deployed-contracts/index.md
Source of truth:
- https://www.notion.so/Unichain-197bf633d0c980519d73d8454d2e9dc6?pvs=4#199bf633d0c98025a834c11cdb5d8f29 deployment log
- https://research.lido.fi/t/steth-wsteth-deployment-on-unichain/9553 (forum post)
- https://research.lido.fi/t/steth-wsteth-deployment-on-unichain/9553/2 (verification report)
- UI: https://superbridge.app/unichain/steth
=> Add proposed Unichain mainnet addresses

docs/deployed-contracts/holesky.md
=> ET contract order fixed

docs/deployed-contracts/index.md
Remove proposed marks for Unichain Mainnet addresses
=> Remove proposed marks for Unichain Mainnet addresses

docs/deployed-contracts/index.md
1. Removed (proposed) tags for Lisk since NEC-4 has no objections https://research.lido.fi/t/nec-4-recognition-of-wsteth-bridge-endpoints-on-lisk-as-canonical/9637
=> Removed (proposed) for Lisk

docs/deployed-contracts/sepolia.md
Update sanity checker address for Sepolia
=> Update sanity checker address for Sepolia

docs/contracts/gate-seal.md, docs/deployed-contracts/index.md, docs/guides/verify-lido-v2-upgrade-manual.md, docs/multisigs/emergency-brakes.md
1. Added new GateSeal
2. Added new CSM GateSeal
3. Updated Lido GateSeal Mainnet config
1. https://www.notion.so/Gate-Seal-Renewal-Action-Plan-2025-18abf633d0c980189ab5c71a8b64edec?pvs=4#18abf633d0c980b2b105f2341f113c41 + Lido Onchain Updates TG channel: 4 March, 12:20 UTC
2. https://www.notion.so/Gate-Seal-Renewal-Action-Plan-2025-18abf633d0c980189ab5c71a8b64edec?pvs=4#193bf633d0c980b6af4bc384335f713c + Lido Onchain Updates TG channel: 4 March, 12:25 UTC
3. GateSeal duration change: https://snapshot.box/#/s:lido-snapshot.eth/proposal/0xa58da73cc4257837ae981d8ad861252f4cbbda7a173a577702f8f93561f57825
=> Renew GateSeal

docs/deployed-contracts/index.md
1. Added consistency to L2 Governance Bridge Executor docs
=> Fix L2 Governance Bridge Executor docs

docs/multisigs/alliance.md, docs/multisigs/other.md, sidebars.js
1. The information about Alliance multisigs was added.
1. https://research.lido.fi/t/lido-alliance-an-ethereum-aligned-ecosystem/7475
2. https://research.lido.fi/t/organize-the-lido-alliance-program-as-a-lido-dao-adjacent-borg/8173
3. https://snapshot.box/#/s:lido-snapshot.eth/proposal/0xa478fa5518769096eda2b7403a1d4104ca47de3102e8a9abab8640ef1b50650c
4. https://research.lido.fi/t/proposal-onboard-drop-to-the-lido-alliance/7556
5. https://research.lido.fi/t/organize-the-lido-alliance-program-as-a-lido-dao-adjacent-borg/8173/32
6. https://snapshot.box/#/s:lido-snapshot.eth/proposal/0x946c9498e76cde24a1475dd786cb119bbfab2b3b5ce95b5177c0818bed91e20b
=> Alliance multisigs

docs/deployed-contracts/holesky.md, docs/deployed-contracts/hoodi.md, docs/deployed-contracts/index.md, sidebars.js
Deployed addresses can be checked against the following PRs:
- https://github.com/lidofinance/core/pull/985
- https://github.com/lidofinance/community-staking-module/pull/437
- https://github.com/lidofinance/gate-seals/pull/32
=> Hoodi deployment

docs/deployed-contracts/index.md, docs/multisigs/alliance.md, docs/multisigs/committees.md
1. Added new multisig addresses to the Deployed Contracts page.
2. Updated details about CSM GateSeal on the committee information page.
1. https://research.lido.fi/t/renew-gateseal-for-the-withdrawal-queue-and-validator-exit-bus-oracle/7081/18
=> MS info updates

docs/guides/oracle-spec/accounting-oracle.md
=> docs: fix some comments

docs/guides/1inch-pool-rewards.md
In the section **"1. Check if you are eligible to claim the reward"**, the sentence:  
> "If there is no your address [here] ..."  
Should be corrected to:  
**"If your address is not listed [here] ..."**  
This makes the sentence grammatically correct.
=> docs: typo fix Update 1inch-pool-rewards.md

docs/deployed-contracts/holesky.md
This pull request adds proposed Dual Governance contracts to the `docs/deployed-contracts/holesky.md` file
* Added a new section titled "Dual Governance" with proposed addresses 
* Added a new section titled "Dual Governance launch contracts" with proposed addresses for the Dual Governance launch voting
=> Add Dual Governance proposed contracts deployed on Holesky

docs/guides/tooling.md
1. Updates to links for new oracle release
1. No onchain changes
=> Update Oracle V5 docs

docs/security/audits.md
1. Add DG audits
2. Add Oracle V5 audits
1. https://github.com/lidofinance/audits/pull/96
2. https://github.com/lidofinance/audits/pull/97
=> Fix: add new audits for DG and Oracle v5

docs/deployed-contracts/hoodi.md
This PR adds Easy Track factories for Simple DVT management
Factories were deployed in https://github.com/lidofinance/easy-track/pull/84
Activated in https://github.com/lidofinance/scripts/pull/375
=> [Hoodi] Simple DVT ET factories deployment

docs/security/audits.md
1. CSMVerifier for Pectra
1. https://github.com/lidofinance/audits/pull/98/files
=> Fix: add CSMVerifier update audits

docs/deployed-contracts/hoodi.md
This PR adds Easy Track factories for Simple DVT management
Factories were deployed in https://github.com/lidofinance/easy-track/pull/88
=> [Hoodi] Stables factories deployment

docs/multisigs/lido-on-x.md
1. Updated Lido-on-Polygon ms info
2. Added related Forum posts and Snapshots
1. https://research.lido.fi/t/lido-for-polygon-proposal-by-shard-labs/816/25
=> updated Lido-on-Polygon ms info

docs/multisigs/committees.md
1. Rotated Marin -> Ivan P in **2.2 Rewards Share Committee**
2. Rotated TheDZhon -> kovalgek in **2.11 Network Expansion Committee**
1. https://research.lido.fi/t/rewards-share-program-2024/6812/21; https://app.safe.global/settings/setup?safe=eth:0xe2A682A9722354D825d1BbDF372cC86B2ea82c8C
2. https://research.lido.fi/t/establishing-the-network-expansion-committee/8788/22
=> RewShare Marin -> Ivan P rotation + NEC TheDZhon -> kovalgek rotation

docs/multisigs/committees.md
1. Rotated Marin -> Ivan P in 4 LOL MSs:
[2.8.1 Liquidity Observation Lab Committee (Ethereum)](https://docs.lido.fi/multisigs/committees#281-liquidity-observation-lab-committee-ethereum)
[2.8.12 Liquidity Observation Lab Committee OP Token Multisig](https://docs.lido.fi/multisigs/committees#2812-liquidity-observation-lab-committee-op-token-multisig)
[2.8.13 Liquidity Observation Lab Committee ARB Token Multisig](https://docs.lido.fi/multisigs/committees#2813-liquidity-observation-lab-committee-arb-token-multisig)
[2.8.15 Liquidity Observation Lab Committee ZK Token Multisig](https://docs.lido.fi/multisigs/committees#2815-liquidity-observation-lab-committee-zk-token-multisig)
1. https://research.lido.fi/t/liquidity-observation-lab-lol-liquidity-strategy-and-application-to-curve-steth-eth-p …
=> Rotate Marin -> Ivan P in 4 LOL MSs

docs/deployed-contracts/hoodi.md
1.  Add AllowedTokensRegistry for Hoodi testnet.
1. Deployed in the [tx](https://hoodi.etherscan.io/tx/0xcbe22a75b4bedd856e18a05c064a42901365f3da4cbe11f5cd6b282f340f24eb) from [Builder](https://hoodi.etherscan.io/address/0xf5436129Cf9d8fa2a1cb6e591347155276550635) that can be found in the [docs](https://docs.lido.fi/deployed-contracts/hoodi).
=> add AllowedTokensRegistry on hoodi

docs/deployed-contracts/hoodi.md
1. Added hoodi DualGovernance contract addresses (as proposed).
1. These contracts were deployed according Hoodi DG deploy plan.
=> Add DualGovernance addresses (proposed) to the hoodi docs

docs/deployed-contracts/hoodi-lidov3.md
ET contracts for hoodi-lidov3 testnet are added
=> Add ET contracts for hoodi-lidov3

docs/deployed-contracts/hoodi-lidov3.md, docs/guides/stvaults/index.md, docs/guides/stvaults/pdg.md
1. Add feedback form
1. https://vaults-hoodi-lidov3.testnet.fi/ (leave feedback btn)
=> Feat: add stVaults feedback form

docs/security/audits.md
1. Add wstETH on Lisk report
1. https://github.com/lidofinance/audits/pull/99
=> Feat: add lisk verification report

docs/contracts/oracle-report-sanity-checker.md, docs/guides/verify-lido-v2-upgrade-manual.md
hey team! I found duplicate words and fixed them.
=> docs: remove consecutive duplicate words

docs/guides/oracle-operator-manual.md
Votes: 
https://vote.lido.fi/vote/186 
https://vote.lido.fi/vote/180
=> fix: update oracle addresses

docs/deployed-contracts/index.md
Remove proposed marks for Swellchain Mainnet addresses
=> Remove proposed marks for swellchain mainnet addresses

docs/guides/lido-tokens-integration-guide.md, docs/integrations/api.md
- Update references from holesky to hoodi in integration guide and api documentation
=> Update references from holesky to hoodi in integration guide and api documentation

docs/lips.md
1. Add LIP-28. Dual Governance
1. https://github.com/lidofinance/lido-improvement-proposals/pull/79
=> Feat: add LIP-28. DG

docs/lips.md
1. LIP-28 changed the status from WIP to Proposed
1. https://github.com/lidofinance/lido-improvement-proposals/pull/83
=> Fix: LIP-28 escalate to 'proposed'

docs/multisigs/committees.md
1. Added Olga K to LOL on Ethereum mainnet msig comp
1. https://research.lido.fi/t/liquidity-observation-lab-lol-liquidity-strategy-and-application-to-curve-steth-eth-pool/5335/22?u=grstepanov
=> Add Olga_K to LOL

docs/deployed-contracts/index.md
This pull request adds proposed Dual Governance contracts to the docs/deployed-contracts/index.md file
Added a new section titled "Dual Governance" with proposed addresses
Added a new section titled "Dual Governance launch contracts" with proposed addresses for the Dual Governance launch voting
=> [Mainnet] Add Dual Governance proposed contracts

docs/guides/stvaults/pdg.md
1. Add deposit data generation details to PDG documentation
=> feat: enhance PDG documentation with deposit data generation details

docs/multisigs/alliance.md, docs/multisigs/committees.md
1. updated LOL and RewShare ms signers
1. https://research.lido.fi/t/liquidity-observation-lab-lol-liquidity-strategy-and-application-to-curve-steth-eth-pool/5335/27
=> LOL and RewShare ms signers update

docs/guides/oracle-spec/accounting-oracle.md, docs/guides/oracle-spec/validator-exit-bus.md
=> docs: fix some typos

docs/multisigs/committees.md
1. new APM committee member added
1. https://research.lido.fi/t/establishing-the-apm-committee/9998/18
=> new APM committee member added

docs/multisigs/committees.md
This pull request updates the `docs/multisigs/committees.md` file by removing the "(Proposed)" label from Dual Governance committee headings, indicating that these committees are now finalized.
=> remove Proposed from DG committees

docs/deployed-contracts/hoodi-lidov3.md
Add addresses of Easy Track contracts for V3 Hoodi testnet-2 deployment.
=> feat: et addresses for v3 hoodi testnet-2

docs/deployed-contracts/index.md, docs/multisigs/lido-contributors-group.md, sidebars.js
1. PML, ATC, RCC ET Factories Removal
1. [Forum post 1](https://research.lido.fi/t/establishment-of-lido-labs-borg-foundation-as-a-lido-dao-adjacent-foundation/9344/25), [forum post 2](https://research.lido.fi/t/establishment-of-lido-ecosystem-borg-foundation-as-a-lido-dao-adjacent-foundation/9345/19)
=> Mark PML, ATC, RCC MSs as obsolete

docs/deployed-contracts/hoodi-lidov3.md
Add addresses of Hoodi ET factories for stVaults
=> chore: add et factories addrs

docs/integrations/wallets.md
1. Explains how to control Earn Page visibility on the Eth Stake Widget
1. https://github.com/lidofinance/ethereum-staking-widget/pull/696/files#diff-ffd2ffbdd740ece21cbd92ea254b25a7f6ebed739bae37c5d4323466321fc2c0
=> feat: explain how to control earn page

.github/CODEOWNERS, docs/lips.md, docs/security/audits.md, docs/security/bugbounty.md
📝 Describe your changes
Update lips.md
Update audits.md
Update bugbounty.md
🔎 Attach a source of truth or evidence that allows reviewers to confirm the changes independently
https://github.com/lidofinance/lido-improvement-proposals
https://github.com/lidofinance/audits
me ;)
=> feat: external updates

docs/multisigs/committees.md
1. Updating Lido Labs Foundation signers + adding public verification for Polar in Tiebreaker committee
1. https://research.lido.fi/t/establishment-of-lido-labs-borg-foundation-as-a-lido-dao-adjacent-foundation/9344/29?u=alex_l
2. https://research.lido.fi/t/establishment-of-lido-labs-borg-foundation-as-a-lido-dao-adjacent-foundation/9344/24?u=alex_l
3. https://research.lido.fi/t/lido-dual-governance-tiebreaker-committee/10047/27?u=alex_l
=> Lido Labs signers update + Tiebraker add details.md
