lidofinance/docs

docs/deployed-contracts.md

The contract in integration is updated, so is the link in docs

Update anchor rewards executor address

---

docs/guides/node-operator-manual.md

Explained how the withdrawal address should be added to the Node Operators Registry before submitting keys.

Add a withdrawal address hint

---

docs/deployed-contracts.md

Goerli setup is full-fledged.
Rinkeby setup based on stubs, but there are Gnosis multisigs exist on Rinkeby and not Goerli.

Doc: add deployed Eeasy Track addrs for Goerli and Rinkeby

---

docs/deployed-contracts.md

New contracts:
- RewardProgramsRegistry (Referral Program): [`0xfCaD241D9D2A2766979A2de208E8210eDf7b7D4F`](https://etherscan.io/address/0xfCaD241D9D2A2766979A2de208E8210eDf7b7D4F) (*inactive*)
- AddRewardProgram (Referral Program): [`0x929547490Ceb6AeEdD7d72F1Ab8957c0210b6E51`](https://etherscan.io/address/0x929547490Ceb6AeEdD7d72F1Ab8957c0210b6E51) (*inactive*)
- RemoveRewardProgram (Referral Program): [`0xE9eb838fb3A288bF59E9275Ccd7e124fDff88a9C`](https://etherscan.io/address/0xE9eb838fb3A288bF59E9275Ccd7e124fDff88a9C) (*inactive*)
- TopUpRewardPrograms (Referral Program): [`0x54058ee0E0c87Ad813C002262cD75B98A7F59218`](https://etherscan.io/address/0x54058ee0E0c87Ad813C002262cD75B98A7F59218) (*inactive*)
Context: 
- https://research.lido.fi/t/setup-lido-referral-program-committee-and-use- …

Feat: add deployed Easy Track factories for Referral Program committee

---

docs/deployed-contracts.md

Referral Program ET factories were activated with the following voting tx:
* https://etherscan.io/tx/0xe37e30ebb742cdf0f002710fb0b13170cfdf201426c5d650e0484a13a4a8f6cf

Fix: remove "inactive" mark from Referral Program ET factories

---

docs/deployed-contracts.md

We have the following voting repo deployed on behalf of Lido DAO
https://etherscan.io/address/0x4ee3118e3858e8d7164a634825bfe0f73d99c792

Doc: add voting repo deployed addr

---

docs/introduction.mdx

This PR adds a link to Kusama docs on intro page.

feat: add kusama link to intro page

---

docs/deployed-contracts.md

There are new Görli addresses:
A first batch (already attached to the Lido protocol)
- Lido implementation: [`0xb16876f11324Fbf02b9B294FBE307B3DB0C02DBB`](https://goerli.etherscan.io/address/0xb16876f11324Fbf02b9B294FBE307B3DB0C02DBB)
- LidoOracle implementation: [`0x7FDef26e3bBB8206135071A52e44f8460A243De5`](https://goerli.etherscan.io/address/0x7FDef26e3bBB8206135071A52e44f8460A243De5)
- NodeOperatorsRegistry implementation: [`0xbb001978bD0d5b36D95c54025ac6a5822b2b1Aec`](https://goerli.etherscan.io/address/0xbb001978bD0d5b36D95c54025ac6a5822b2b1Aec)
- LidoExecutionLayerRewardsVault: [`0x94750381bE1AbA0504C666ee1DB118F68f0780D4`](https://goerli.etherscan.io/address/0x94750381bE1AbA0504C666ee1DB118F68f0780D4)
A second batch (to be attached)
- DepositSecurityModule: …

Feat: add goerli merge-ready deployed contracts

---

docs/guides/node-operator-manual.md

nominated --> denominated (this is proper in this context)
StETH --> stETH (this is the official styling used by Lido)

Wording and `stETH` styling

---

docs/contracts/deposit-security-module.md

Update `DepositSecurityModule` docs:
* Add `setLastDepositBlock` and `getLastDepositBlock` methods which were introduced for the merge-ready protocol service pack
* Reorganize a bit some view and non-view methods.
---
:warning: Feel free to review, but, please, don't merge yet.

Fix: update DepositSecurityModule docs (merge-ready protocol round 2)

---

docs/guides/steth-integration-guide.md

Explain the current `permit` implementation state for wstETH and stETH properly.
See also the following issue: https://github.com/lidofinance/lido-dao/issues/440

Fix: ERC20 Permit for wstETH and stETH

---

docs/guides/node-operator-manual.md

- Added more info about about EL rewards config and made it clearer that it's required for both priority fees as well as possible MEV rewards, added some extra links to possible client configuration examples, fixed link to Nimbus docs (it was pointing to a page that didn't have any info about fee recipient -- we can update once their docs are updated)
- fixed a small typo

Add additional info about EL Rewards Configuration for Node Operators

---

docs/contracts/stable-swap-state-oracle.md
docs/contracts/steth-price-feed.md
docs/deployed-contracts.md
sidebars.js

- Remove the items from the sidebar
- Put warning plates.
- Declare internal price feed as a reserve.

Discourage steth-price-feed usage by external integrations

---

docs/introduction.mdx

Add Lido on Ethereum APR heading to introduction page

fix: heading for Ethereum APR

---

docs/contracts/lido-oracle.md

Added a small disclaimer on how there could be no oracle reports for extended periods of time in case of no Consensus Layer finality

Add disclaimer on no finality

---

docs/deployed-contracts/index.md

- swapped Arb and Opti Curve rewards manager addresses to meet the alphabetical order
- added Chainlink wstETH/stETH exchange rate feeds for L2s

Chainlink wstETH/stETH exchange rate feeds for L2s

---

docs/deployed-contracts/goerli.md

Use the old contract version because of the already provided `stETH` allowance.

Fix: rollback burner addr on Goerli

---

.github/CODEOWNERS

Define [`CODEOWNERS`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for the deployed and documented contracts.

Access: codeowners for contracts

---

docs/guides/steth-integration-guide.md

Fixes for the integration guide with V2-related changes.
- Removed some things that become outdated with V2 
- Added Withdrawals section mostly based on the note by @grstepanov https://hackmd.io/za6A56h2RGeJKrVd3if7UQ?view

V2 integration guide

---

docs/guides/steth-integration-guide.md

https://docs.lido.fi/guides/steth-integration-guide/#rewards-accounting
Nice to have to read this as a list, not text:
```
1. User wraps 1 stETH and gets 0.9803 wstETH (1 stETH = 0.9803 wstETH) 
2. A rebase happens, the wstETH price goes up by 5% 
3. User unwraps 0.9803 wstETH and gets 1.0499 stETH (1 stETH = 0.9337 wstETH)
```
https://github.com/lidofinance/docs/issues/227#issue-1780592876

fix: Basic rewards list display #227

---

docs/contracts/oracle-report-sanity-checker.md

Propose a few edits to be done for #225 :pray:

Fix: some edit proposals

---

docs/contracts/legacy-oracle.md

The PR partially addresses #217 with regards to `LegacyOracle`

Doc: LegacyOracle rework

---

docs/guides/easy-track-guide.md
docs/guides/node-operators/validator-keys.md

Added an extra step for the Validator Keys part, just a reference to the easy track guide. (avoiding redundancy).
Changed the easy track limit to 20 from 12 (in the guide).
some readability changes to both the Validator Keys part as well as the easy track guide.

Updated NO Guide with reference to Easy track guide

---

docs/contracts/wsteth.md

Update wstETH docs

---

docs/contracts/lido.md

Related to #217 
- line width 80 to better review in GH PR
- semantic structure for ABI reference
- removed `Parameters` and `Returns` subheaders (too noisy and repetitive)
- improve wording somewhere

Better docs for Lido

---

docs/guides/lido-tokens-integration-guide.md

- add all of the AAVE v3 markets existing for wstETH
- add Uniswap V3 liquidity wstETH:ETH pool
- change the main Balancer V2 pool (stable pool → **composable** stable pool) by wstETH TVL

Feat: integration guide — add AAVE v3 wstETH, add Uni v3

---

package.json
yarn.lock

```js
info Direct dependencies
├─ @docusaurus/plugin-client-redirects@2.4.3
├─ @docusaurus/preset-classic@2.4.3
└─ @docusaurus/theme-mermaid@2.4.3
info All dependencies
├─ @docusaurus/cssnano-preset@2.4.3
├─ @docusaurus/plugin-client-redirects@2.4.3
├─ @docusaurus/plugin-debug@2.4.3
├─ @docusaurus/plugin-google-analytics@2.4.3
├─ @docusaurus/plugin-google-gtag@2.4.3
├─ @docusaurus/plugin-google-tag-manager@2.4.3
├─ @docusaurus/plugin-sitemap@2.4.3
├─ @docusaurus/preset-classic@2.4.3
├─ @docusaurus/theme-classic@2.4.3
├─ @docusaurus/theme-mermaid@2.4.3
```

Bump: docusaurus 2.4.1 -> 2.4.3

---

.github/CODEOWNERS

- `deployed-contracts` to `lido-dao-ops-team`
- `guides` to `lido-dao-ops-team`
- except tokens integration guide: `lido-eth-protocol`
- `security` to `lido-eth-protocol`
- except `bugbounty` to `lido-dao-ops-team`

Codeowners: update ownership

---

docs/guides/node-operators/exits/tooling-setup.md

Aragon is often running into rpc issues, so i've added the option to do a direct getMembers() call on etherscan to each chain as well. We've been getting q's from operators about this.

Update tooling-setup.md to include Holesky oracle allowlist

---

docs/deployed-contracts/goerli.md
docs/deployed-contracts/index.md

---
:warning: Please don't merge yet while the snapshot vote haven't being finished

Doc: remove the 'Proposed' mark for the about to be recognized L2s

---

docs/multisigs/emergency-brakes.md

Lido DAO recognized Mantle & zkSunc bridges endpoints as canonical, adding 2 new Emergency Brakes multisigs. Documentation updated with the new multisigs details.
For verification refer to the following resources:
**Mantle:** 
Snapshot: https://snapshot.org/#/lido-snapshot.eth/proposal/0x349fa7409a99683405e71ddebaf5068f3dee7d4e6c9e4375198c4dc10c899bb9
Contracts: https://docs.lido.fi/deployed-contracts/#mantle-part
**zkSync:** 
Snapshot: https://snapshot.org/#/lido-snapshot.eth/proposal/0xd6c4a71c36bef27c4b5997223bd8612fe19177b46b238e78802a4a27fd5cdc9e
Contracts: https://docs.lido.fi/deployed-contracts/#zksync-era-part

add new emergency brakes msigs

---

docs/multisigs/committees.md

Update compositions of LOL multisigs on mainnet and L2s

LOL msig rotations Jan-24

---

docs/integrations/api.md

The link is mentioned inside the `integrations/api.md` doc

Fix: legacy oracle event broken link

---

docs/contracts/accounting-oracle.md
docs/contracts/burner.md
docs/contracts/deposit-security-module.md
docs/contracts/hash-consensus.md
docs/contracts/legacy-oracle.md
docs/contracts/lido.md
docs/contracts/validators-exit-bus-oracle.md
docs/guides/checking-aragon-vote.md
docs/guides/easy-track-guide.md
docs/guides/etherscan-voting.md
docs/guides/jumpgates.md
docs/guides/lido-tokens-integration-guide.md
docs/guides/node-operators/el-rewards-configuration.md
docs/guides/node-operators/validator-keys.md
docs/guides/oracle-operator-manual.md
docs/guides/protocol-levers.md
docs/guides/verify-lido-v2-upgrade-manual.md
docs/integrations/aave/aip.md
docs/introduction.mdx
docusaurus.config.js
package.json
yarn.lock

---
- Migration path: https://docusaurus.io/docs/migration/v3
- Docusaurus 3.0 announce: https://docusaurus.io/blog/releases/3.0
- Docusaurus 3.1 announce: https://docusaurus.io/blog/releases/3.1

Feat: Upgrade docusaurus v2 → v3

---

docs/introduction.mdx

- fix broken link in CL section of intro to point to correct page in the operator portal

fix: broken link in intro to operator portal

---

docs/deployed-contracts/index.md
docs/multisigs/committees.md

Adding new LOL multisigs for AAVE rewards (single address on five networks). Removing old AAVE LOL multisigs (Base and Optimism)

Add LOL AAVE rewards multisigs

---

docs/contracts/withdrawal-queue-erc721.md

Turns out > and < statements should have been formulated as ≥ and ≤
Fixes #357

Fix: equal to wording

---

docs/deployed-contracts/index.md
docs/deployed-contracts/sepolia.md

An update to deployed contracts with a.DI and (proposed) wstETH contracts.
Based on:
- https://research.lido.fi/t/network-expansion-workgroup-initiative-governance-decision-forwarding-to-non-l2-networks-lip-24/7446/8
- https://research.lido.fi/t/wormhole-x-axelar-lido-bridge-implementation-for-wsteth-on-bnb-chain/6012/30#deployment-details-and-contract-addresses-4

Docs: a.DI + wstETH contracts

---

docs/deployed-contracts/index.md
docs/deployed-contracts/sepolia.md
docs/guides/lido-tokens-integration-guide.md
docs/token-guides/wsteth-bridging-guide.md

Just rename all of the `Lido on L2` mentions to `Lido Multichain` to follow the up-to-date branding approach.

Feat: Lido Multichain

---

docs/deployed-contracts/sepolia.md

Update sanity checker address on sepolia after negative rebase deployment
Address can be checked via LidoLocator proxy https://sepolia.etherscan.io/address/0x8f6254332f69557A72b0DA2D5F0Bc07d4CA991E7#readProxyContract
Updated locator implementation is here https://sepolia.etherscan.io/address/0x144c3832364aFF481854aE156601993B66EfD12c

Update sanity checker address on sepolia 

---

docs/contracts/lido.md
docs/integrations/wallets.md

Fix Lido Referral Program links
https://lido.fi/referral is no longer available (as well as https://lido.fi/rewards-share it redirects to). I propose to change the current link to the forum post: https://research.lido.fi/t/rewards-share-program-2024/6812

fix: referral program

---

docs/guides/tooling.md

Updating the docker image hash for the new version of the Council daemon
- github job with sha hash (https://github.com/lidofinance/infra-mainnet/actions/runs/11613711799/job/32340754079)

feat: update docker hash for council daemon

---

docs/lips.md

Lido has moved to using new Solidity versions and uses upgradeable contracts from OpenZeppelin, which already include the `Initializable` contract. To avoid maintaining two initialization approaches simultaneously (LIP-10 and OZ Initializable), we propose deprecating LIP-10 and later relying on OpenZeppelin’s Initializable contract for upgradeable contracts.

feat: lip-10 deprecation

---

docs/contracts/eip712-steth.md
docs/ipfs/release-flow.md
docs/staking-modules/csm/contracts/CSAccounting.md

1. docs/contracts/eip712-steth.md:
Added "the" before "complete support"
Reason: definite article needed as it refers to specific support
2. docs/ipfs/release-flow.md:
Added "the" before "CI process"
Changed "is" to "are" for "details are attached"
Reason: definite article needed before CI process and verb agreement with plural "details"
3. docs/contracts/lido-locator.md:
Changed "Return" to "Returns"
Reason: consistency with other function descriptions in documentation

 fix grammar in documentation

---

docs/guides/validator-ejector-guide.md
docs/multisigs/committees.md

Changes made:
1. docs/guides/validator-ejector-guide.md
- Old: https://github.com/lidofinance/lido-dao/blob/feature/shapella-upgrade/contracts/0.8.9/StakingRouter.sol
- New: https://github.com/lidofinance/core/blob/master/contracts/0.8.9/StakingRouter.sol
Reason: Updated link to current location in main repository
2. docs/multisig/committees.md
- Old: 0x1F809D2cb72a5Ab13778811742050eDa876129b63
- New: 0x1F809D2cb72a5Ab13778811742050eDa876129b6
Reason: Fixed incorrect contract address (removed extra '3' digit at the end)
These changes improve documentation accuracy and fix contract address errors.

validator-ejector-guide.md and multisig/committees.md

---

README.md
docs/contracts/oracle-report-sanity-checker.md

Files changed:
1. docs/contracts/oracle-report-sanity-checker.md:
- Old: "maximul"
- New: "maximum"
2. README.md:
- Old: "appereance"
- New: "appearance"
- Old: "builded"
- New: "built"
1. Fixes spelling errors for better accuracy and readability
2. Improves technical documentation professionalism
3. Maintains consistent English language usage

Fix multiple typos in documentation

---

docs/token-guides/steth-on-aave-caveats.md
docs/token-guides/wsteth-bridging-guide.md

Hey! I came across a couple of small issues while reviewing the docs. Here's what I updated:
1. In the file `docs/token-guides/steth-on-aave-caveats.md`, I noticed a typo where "flashoan" was used instead of the correct term "flashloan." I’ve corrected it to ensure consistency and accuracy.
2. In the file `docs/token-guides/wsteth-bridging-guide.md`, there was a minor grammatical issue. The phrase "If any of R-1...R-4 isn’t followed, there can be less likelihood of the NEC recognition." needed a slight adjustment to use "aren’t" instead of "isn’t," since we're referring to multiple items (R-1, R-2, R-3, and R-4). I’ve corrected this to:  
"If any of R-1...R-4 aren’t followed, there can be less likelihood of the NEC recognition."
Both changes should improve the clarity and correctness of …

docs: Fix minor typos and grammar improvements in token guides

---

docs/contracts/insurance.md

I noticed that in the `transferERC1155` method, the event `ERC721Transferred` was incorrectly referenced in the comments. Since this method is designed to transfer ERC1155 tokens, the event should be `ERC1155Transferred` instead.
I've corrected the event name to reflect the proper standard and ensure consistency with the method's functionality.

docs: Corrected Event Name in transferERC1155 Method Update insurance.md

---

README.md

I’ve corrected several typographical and grammatical errors in the documentation to improve clarity and accuracy. The key changes include fixing capitalization issues with "GitHub", adding necessary articles like "the", and improving sentence structure for better readability. Here's a summary of the changes:
- "hosted via Github Pages from branch gh-pages of this repository." → "hosted via GitHub Pages from the gh-pages branch of this repository."
- "Documentation pages stored in /docs folder." → "Documentation pages are stored in the /docs folder."
- "The appearance of sidebar controlled manually via sidebars.js file." → "The appearance of the sidebar is controlled manually via the sidebars.js file."
- "By default new added pages don't added to sidebar automatically." → "By default, …

docs: Fixing typos and improving sentence clarity Update README.md

---

docusaurus.config.js

This seems to get used in a bunch of headers on every docs page, and links to the old lidofinance.github.com.

Update github link in docusaurus.config.js

---

docs/ipfs/apps-list.md

Updates to IPFS CIDs:
* [`docs/ipfs/apps-list.md`](diffhunk://#diff-49d93c31a1141c04251dd076a07653a18c1046b275240056069efeb2987efcafL7-R10): Updated the CID for the Lido Ethereum Liquid Staking Widget
* [`docs/ipfs/apps-list.md`](diffhunk://#diff-49d93c31a1141c04251dd076a07653a18c1046b275240056069efeb2987efcafL7-R10): Updated the IPFS Gateway for the stETH as Anchor collateral widget to a new IPFS gateway.

feat: update IPFS CID for Lido Ethereum Liquid Staking Widget

---

docs/deployed-contracts/holesky.md
docs/deployed-contracts/index.md
docs/guides/verify-lido-v2-upgrade-manual.md
docs/multisigs/committees.md
docs/staking-modules/csm/permissions.md
docs/token-guides/wsteth-bridging-guide.md

1. Proposed new Holesky GateSeal
2. Proposed new Holesky CSM GateSeal
3. Fixed GateSeal spelling across docs
1. https://www.notion.so/Gate-Seal-Renewal-Action-Plan-2025-18abf633d0c980189ab5c71a8b64edec?pvs=4#18abf633d0c9803693cbf4e83cae47dd
2. https://www.notion.so/Gate-Seal-Renewal-Action-Plan-2025-18abf633d0c980189ab5c71a8b64edec?pvs=4#193bf633d0c980968346c27c604cb10f

Gate Seal 2025 Holesky

---

docs/deployed-contracts/index.md

1. Remove obsolete price feeds from the deployed contract list
2. Add up-to-date price feeds based on the wstETH/stETH rate approach
1. https://data.chain.link/feeds/linea/mainnet/wsteth-steth-exchange-rate
2. https://data.chain.link/feeds/bsc/mainnet/wsteth-steth-exchange-rate
3. https://data.chain.link/feeds/optimism/mainnet/wsteth-steth%20exchangerate
4. https://data.chain.link/feeds/base/base/wsteth-steth%20exchangerate
5. https://data.chain.link/feeds/arbitrum/mainnet/wsteth-steth%20exchangerate
6. https://data.chain.link/feeds/zksync/zksync/wsteth-steth%20exchangerate
7. https://data.chain.link/feeds/scroll/mainnet/wsteth-steth%20exchangerate
8. https://docs.lido.fi/guides/lido-tokens-integration-guide#integration-utilities-rate-and-price-feeds

Fix: update (w)stETH deployed contracts feeds

---

docs/deployed-contracts/holesky.md
docs/deployed-contracts/index.md
docs/guides/address-ownership-guide.md

DAO Ops unit name fixed

---

docs/deployed-contracts/hoodi.md

This PR updates the URLs for Hoodi contract addresses in the docs/deployed-contracts/hoodi.md file to use Etherscan instead of Blockscout
The PR is branched from https://github.com/lidofinance/docs/pull/563 and has an updated address for CSVerifier contract

Replace block explorer for Hoodi addresses to Etherscan

---

docs/ipfs/security.md

I fixed a issue where "RPC nodes urls" was used instead of "RPC node URLs".

docs: Corrected typo in "RPC nodes urls"

---

docs/guides/validator-ejector-guide.md

I corrected a small typo in the "Encrypting Messages" section. The phrase "exit message are" was updated to "exit messages are" to improve the grammar and clarity of the text.

docs: fixed typo in "Encrypting Messages" section

---

docs/guides/deposit-security-manual.md

The word **"member"** should be plural to match the context. Corrected sentence:  
**"Also, members have to run `DSC Daemon` that monitors the validators’ public keys in the `DepositContract` and in all Staking Modules."**

Doc: Typo Fix deposit-security-manual.md

---

docs/ipfs/apps-list.md

This pull request includes a small update to the `docs/ipfs/apps-list.md` file. The change updates the URLs for the CID links to use a different IPFS gateway.
* Updated CID links to use `dweb.link` instead of `flk-ipfs.xyz` in `docs/ipfs/apps-list.md`.
1. https://ipfs.github.io/public-gateway-checker/

Update IPFS app links to use dweb.link for improved accessibility

---

docs/lips.md

1. Lift `LIP-27` status from `WIP` to `Proposed`
1. https://github.com/lidofinance/lido-improvement-proposals/pull/76

Fix: lift LIP-27 to the proposed state

---

docs/deployed-contracts/index.md

This pull request updates the `docs/deployed-contracts/index.md` file to reflect the current state of deployed contracts. 
Updates to deployed contracts documentation:
* Removed outdated `CSVerifier` contract entries that were proposed for removal or replacement.
* Consolidated the `CSVerifier` contract entry to reflect the current deployment.

Remove proposed mark on cs verifier address

---

docs/guides/node-operators/validator-keys.md

Changed the erroneous "withdrawal address" with "node operator's registry address". 
Also fixed some grammatical errors in the same paragraph.
1. Changed the erroneous "withdrawal address" with "node operator's registry address". 
2. fixed some grammatical errors in the same paragraph.
1. Node Operator registry address is called a "reward address":https://docs.lido.fi/contracts/node-operators-registry

fix: wrong name for registry address in validator-keys.md

---

docs/deployed-contracts/holesky.md
docs/deployed-contracts/hoodi.md
docs/deployed-contracts/sepolia.md

1. Hoodi is the main testnet now
2. Holešky is deprecated

Fix: Make Hoodi to be the primary testnet

---

docs/contracts/staking-router.md

This PR fixes a mistake in the description of `reportRewardsMinted` method in `StakingRouter`

Fix StakingRouter reportRewardsMinted method description

---

docs/deployed-contracts/hoodi.md

1. Easy Track factories for token transfers list on Hoodi updated
1. Vote on hoodi: https://vote-hoodi.testnet.fi/vote/31
2. Deploy configs / logs
deploy_config = deployment.AllowedRecipientsSingleTokenFullSetupDeployConfig(
token="0x3508A952176b3c15387C97BE809eaffB1982176a",
limit=100*10**18,
period=6,
spent_amount=0,
trusted_caller="0x418B816A7c3ecA151A31d98e30aa7DAa33aBf83A",
titles=["Test funder – stETH, multiple recipients"],
recipients=["0x418B816A7c3ecA151A31d98e30aa7DAa33aBf83A"],
)
AllowedRecipientsRegistryDeployed: 0x7E33f2192c2cEC339493B9193110BC0510d6CBD2
TopUpAllowedRecipientsDeployed: 0xE5aE943A3AEFA44AD16438Bc3D2cA7654103F985
AddAllowedRecipientDeployed: 0x8f05Cc4cC42745E9723E105D38638683f162e1d9
RemoveAllowedRecipientDeployed: 0x86E10ffC7c67A92e0c5E58ae42945213da43D0c7 …

Easy Track factories for token transfers list on Hoodi updated

---

docs/ipfs/apps-list.md

This pull request updates the IPFS gateway URLs in the `docs/ipfs/apps-list.md` documentation. The links for the Lido Ethereum Liquid Staking Widget and the stETH as Anchor collateral widget now use the `ipfs.inbrowser.link` gateway instead of `ipfs.dweb.link`.
1.

fix: update IPFS links to use inbrowser.link for Lido applications

---

docs/guides/oracle-operator-manual.md
docs/guides/tooling.md

Oracle V6 review. 
All hashes could be checked in Composable Security audit report.
Removed participants list because it's outdated

feat: Oracle v6 release
